### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by GkevinOD**

### CODE REVIEW

**Comment by 593394978** [comment]
i try to use nox , but it can't not work.
 i used au3 tool to find emulator title and instance and change it.
after that i use the bot , but tip is unknow for all location.
all the locations have to be reset? 
help

**Comment by GkevinOD** [comment]
@593394978 Hello, the default title of the new versions of nox should be 'NoxPlayer' and the instance should not have been changed for any version. Please provide a screenshot of Nox window and the bot config so I can analyze the problem.

**Comment by 593394978** [comment]
today, i try it again, but still the same way

**Comment by dcloud102** [comment]
Did you change nox settings acording to the instructions on here? Resolutions of 800 x 552?

**Comment by 593394978** [comment]
for the farm golem mode,
it can't not buy the soulstones.
Collect hourly: The middle of the tree one click

**Comment by 593394978** [comment]
@dclound102 i change it

**Comment by dcloud102** [comment]
Try going typing in _CaptureRegion("test.bmp") in the test code box and click the button. See what image it captures. The test.bmp will be place in the root folder of the bot.

**Comment by dcloud102** [comment]
Once the location is unknown, you can click the set location button and name that location. Like map, or village

**Comment by 593394978** [comment]
@dcloud102 ok, i will try it later

**Pull request merged**
